name: Build
run-name: ${{ github.actor }} is building heymoon/php-vector-tile-data-provider-tester
on:
  workflow_dispatch: {}
  push:
    paths:
      - tests/runtime
jobs:
  build:
    name: Build
    runs-on: Linux
    steps:
      - uses: actions/checkout@v1
      - run: make push && make clean
