name: Build
run-name: ${{ github.actor }} is building heymoon/mvt-tools-tester image
on:
  push:
    paths:
      - Dockerfile
      - .dockerignore
jobs:
  build:
    name: Build
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3
      - run: make push && make clean
