name: Test
run-name: ${{ github.actor }} is testing heymoon/mvt-tools
on: workflow_dispatch
jobs:
  test:
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3
      - run: make composer
      - run: make audit
      - name: Upload test results
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: test-reports/tests.xml
      - name: Upload coverage results
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: test-reports/coverage.xml
          badge: true
      - name: PHPMD
        run: make phpmd
      - run: make clean
